Añado lsusbdiscs y lscommands

diff --git a/tools/fs-tools b/tools/fs-tools
--- a/tools/fs-tools
+++ b/tools/fs-tools
@@ -38,8 +38,13 @@ shift
 source "$LIB_DIR/$util.sh"
 
 case "$util" in
+    "lscommands")   #lista los comandos disponibles
+        lscommands
+        exit $?
+        ;;
+
     "lsfs")     # lista el filesystem
-       if [ "$verbose" ]; then
+        if [ "$verbose" ]; then
             echo -en "\n$msg_emphasis"
             printf '\055%.0s' {1..70}
             printf '\n%-40s%30s\n' "$0 lsfs" "$currentdate"
@@ -69,6 +74,23 @@ case "$util" in
             lsdiscs
             exit $?
         fi
+        ;;
+    
+    "lsusbdiscs")
+        if [ "$verbose" ]; then
+            echo -en "\n$msg_emphasis"
+            printf '\055%.0s' {1..70}
+            printf '\n%-40s%30s\n' "$0 lsfs" "$currentdate"
+            printf '\055%.0s' {1..70}
+            printf '\n%-23s\t%-40s\n' "device" "name"
+        fi
+        lsusbdiscs "$@"
+        retcode=$?
+        if [ "$verbose" ]; then
+            printf '\055%.0s' {1..70}; echo ""
+            echo -e $msg_end
+        fi
+        exit $retcode
         ;;
 
     "lsparts")  # lista las particiones
@@ -121,9 +143,8 @@ case "$util" in
         ;;
 
     *)          # deconocido
-        echo -e $msg_error
-        echo -en " Error: el comando $msg_panic'$1'$msg_error no existe "
-        echo -e $msg_end
+        echo -e $msg_error"Error: el comando $msg_panic'$util'$msg_error no existe"$msg_end
+        echo -e $msg_emphasis"utilice 'fs-tools lscommands para un listado de comandos"$msg_end
         exit 254
         ;;
 esac
