Añado mountpoint y estandarizo el mecanismo de fs-tools

diff --git a/tools/fs-tools b/tools/fs-tools
--- a/tools/fs-tools
+++ b/tools/fs-tools
@@ -34,134 +34,26 @@ fi
 util="$1"
 shift
 
+if [ ! -r "$LIB_DIR/$util.sh" ]; then
+    echo -e $msg_error"Error: el comando $msg_panic'$util'$msg_error no existe"$msg_end
+    echo -e $msg_emphasis"utilice 'fs-tools lscommands' para un listado de comandos"$msg_end
+    exit 254
+fi
+
 # carga la función solicitada
 source "$LIB_DIR/$util.sh"
 
-case "$util" in
-    "lscommands")   #lista los comandos disponibles
-        lscommands
-        exit $?
-        ;;
-
-    "lsfs")     # lista el filesystem
-        if [ "$verbose" ]; then
-            echo -en "\n$msg_emphasis"
-            printf '\055%.0s' {1..70}
-            printf '\n%-40s%30s\n' "$0 lsfs" "$currentdate"
-            printf '\055%.0s' {1..70}; echo ""
-        fi
-        lsfs
-        retcode=$?
-        if [ "$verbose" ]; then
-            printf '\055%.0s' {1..70}; echo ""
-            echo -e $msg_end
-        fi
-        exit $retcode
-        ;;
-
-    "lsdiscs")  # lista los discos en el systema
-        if [ "$verbose" ]; then
-            echo -en "\n$msg_emphasis"
-            printf '\055%.0s' {1..70}
-            printf '\n%-40s%30s\n' "$0 lsdiscs" "$currentdate"
-            printf '\055%.0s' {1..70}; echo ""
-            lsdiscs -v
-            retcode=$?
-            printf '\055%.0s' {1..70}; echo ""
-            echo -e $msg_end
-            exit $retcode
-        else
-            lsdiscs
-            exit $?
-        fi
-        ;;
-    
-    "lsusbdiscs")
-        if [ "$verbose" ]; then
-            echo -en "\n$msg_emphasis"
-            printf '\055%.0s' {1..70}
-            printf '\n%-40s%30s\n' "$0 lsfs" "$currentdate"
-            printf '\055%.0s' {1..70}
-            printf '\n%-23s\t%-40s\n' "device" "name"
-        fi
-        lsusbdiscs "$@"
-        retcode=$?
-        if [ "$verbose" ]; then
-            printf '\055%.0s' {1..70}; echo ""
-            echo -e $msg_end
-        fi
-        exit $retcode
-        ;;
-
-    "lsparts")  # lista las particiones
-        if [ "$verbose" ]; then
-            echo -en "\n$msg_emphasis"
-            printf '\055%.0s' {1..70}
-            printf '\n%-40s%30s\n' "$0 lsparts" "$currentdate"
-            printf '\055%.0s' {1..70}; echo ""
-            lsparts -v "$@"
-            retcode=$?
-            printf '\055%.0s' {1..70}; echo ""
-            echo -e $msg_end
-            exit $retcode
-        else
-            lsparts "$@"
-            exit $?
-        fi
-        ;;
-
-    "lsdev")    # obtiene el device
-        if [ "$verbose" ]; then
-            echo -en "\n$msg_emphasis"
-            printf '\055%.0s' {1..70}
-            printf '\n%-40s%30s\n' "$0 lsdev" "$currentdate"
-            printf '\055%.0s' {1..70}; echo ""
-            lsdev -v $@
-            retcode=$?
-            printf '\055%.0s' {1..70}; echo ""
-            echo -e $msg_end
-            exit $retcode
-        else
-            lsdev $@
-            exit $?
-        fi
-        ;;
-
-    "lsuuid")   # obtiene el UUID
-        lsuuid "$@"
-        exit $?
-        ;;
-    
-    "lslabel")  # obtiene el LABEL
-        lslabel "$@"
-        exit $?
-        ;;
-
-    "fstype")   # obtiene tipo del sistema de ficheros
-        fstype "$@"
-        exit $?
-        ;;
-
-    "sizedisc") #obtiene el tamaño del disco
-        if [ "$verbose" ]; then
-            echo -en "\n$msg_emphasis"
-            printf '\055%.0s' {1..70}
-            printf '\n%-40s%30s\n' "$0 lsparts" "$currentdate"
-            printf '\055%.0s' {1..70}; echo ""
-            sizedisc -v "$@"
-            retcode=$?
-            printf '\055%.0s' {1..70}; echo ""
-            echo -e $msg_end
-            exit $retcode
-        else
-            sizedisc "$@"
-            exit $?
-        fi
-        ;;
-
-    *)          # deconocido
-        echo -e $msg_error"Error: el comando $msg_panic'$util'$msg_error no existe"$msg_end
-        echo -e $msg_emphasis"utilice 'fs-tools lscommands para un listado de comandos"$msg_end
-        exit 254
-        ;;
-esac
+if [ "$verbose" ]; then
+    echo -en "\n$msg_emphasis"
+    printf '\055%.0s' {1..70}
+    printf '\n%-40s%30s\n' "$0 $util" "$currentdate"
+    printf '\055%.0s' {1..70}; echo ""
+    $util -v $@
+    retcode=$?
+    printf '\055%.0s' {1..70}; echo ""
+    echo -e $msg_end
+    exit $retcode
+else
+    $util $@
+    exit $?
+fi
